services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME}-php
    build:
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
      context: .
      dockerfile: ./docker/dockerfiles/php/Dockerfile
    volumes:
      - ./:${APP_PATH}
      - ./docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/config/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    build:
      context: .
      dockerfile: ./docker/dockerfiles/nginx/Dockerfile
    ports:
      - "${APP_WEB_PORT}:80"
    volumes:
      - ./:${APP_PATH}
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - php

  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  npm:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/node/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-npm
    volumes:
      - ./:${APP_PATH}:cached
    networks:
      - app-network
    working_dir: ${APP_PATH}
    profiles: [ "npm" ]
    entrypoint: [ 'npm' ]
    ports:
      - "${APP_VITE_PORT}:5173"

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
